name: flutter_hooks_lint_plugin
description: a lint plugin for flutter_hooks
repository: https://github.com/mj-hd/flutter_hooks_lint_plugin
version: 0.7.0

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  analyzer: ^14.1.0
  analyzer_plugin: ^0.14.14
  analysis_server_plugin: ^0.3.20
  logging: ^1.0.0
  yaml: ^3.1.0

dev_dependencies:
  async: ^2.13.1
  lints: 2.0.1
  test: ^1.31.2
  analyzer_testing: ^0.3.4
  test_reflective_loader: ^0.4.0
